INSERT INTO "EXEMPLO"."TAB_CARTAO"(ID, TIPO_CARTAO) VALUES (1, 'CREDITO');
INSERT INTO "EXEMPLO"."TAB_CARTAO"(ID, TIPO_CARTAO) VALUES (2, 'DEBITO');

INSERT INTO "EXEMPLO"."TAB_DEBITO"(ID, DESCRICAO) VALUES (1, 'CREDITO');
INSERT INTO "EXEMPLO"."TAB_DEBITO"(ID, DESCRICAO) VALUES (2, 'DEBITO');