CREATE TABLE IF NOT EXISTS "EXEMPLO"."TAB_VALIDACAO"
(
    "ID" NUMBER PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS "EXEMPLO"."TAB_CARTAO"
(
    "ID" NUMBER PRIMARY KEY,
    "TIPO_CARTAO" VARCHAR(50)
);

INSERT INTO "EXEMPLO"."TAB_CARTAO"(ID, TIPO_CARTAO) VALUES (1, 'CREDITO');